<?php
declare(strict_types=1);
require_once __DIR__ . '/../api/config.php';
$from=trim((string)($_GET['from']??'')); $to=trim((string)($_GET['to']??''));
$sql="SELECT moved_at,uid,item_name,item_code,quantity,from_zone,to_zone,from_department,to_department,moved_by,device_uid,notes FROM rfid_boh_foh_movements";
$where=[];$types='';$params=[];
if($from!==''&&preg_match('/^\\d{4}-\\d{2}-\\d{2}$/',$from)){ $where[]='moved_at >= ?';$types.='s';$params[]=$from.' 00:00:00'; }
if($to!==''&&preg_match('/^\\d{4}-\\d{2}-\\d{2}$/',$to)){ $where[]='moved_at <= ?';$types.='s';$params[]=$to.' 23:59:59'; }
if($where)$sql.=' WHERE '.implode(' AND ',$where); $sql.=' ORDER BY moved_at DESC';
$stmt=$conn->prepare($sql); if($types!=='')$stmt->bind_param($types,...$params); $stmt->execute();$result=$stmt->get_result();
$rows=[];$total=0;while($r=$result->fetch_assoc()){$rows[]=$r;$total+=(int)$r['quantity'];}$stmt->close();
function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BOH → FOH Reports</title><style>
*{box-sizing:border-box}body{margin:0;background:#071018;color:#eef7fb;font-family:Inter,Segoe UI,Arial;padding:18px}.wrap{max-width:1250px;margin:auto}.card{background:#101c26;border:1px solid #263746;border-radius:20px;padding:20px;margin-bottom:16px}h1{margin:0 0 8px}.muted{color:#9db0ba}.filters{display:grid;grid-template-columns:1fr 1fr auto auto auto;gap:10px;align-items:end}label{font-size:12px;color:#9db0ba}input,button,a{padding:11px 13px;border-radius:10px;border:1px solid #31505d}input{width:100%;background:#0b151d;color:#fff}button,a{background:#20c997;color:#06120f;font-weight:700;text-decoration:none;cursor:pointer}.stats{display:flex;gap:12px;flex-wrap:wrap}.stat{min-width:180px;background:#0b151d;border:1px solid #263746;border-radius:14px;padding:14px}.stat b{font-size:22px;display:block}.stat span{font-size:12px;color:#9db0ba}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1000px}th,td{padding:9px;border-bottom:1px solid #263746;text-align:left;font-size:13px}th{color:#9db0ba;font-size:11px;text-transform:uppercase}@media(max-width:700px){.filters{grid-template-columns:1fr 1fr}.filters button,.filters a{grid-column:span 1}}
</style></head><body><div class="wrap"><div class="card"><h1>BOH → FOH Movement Reports</h1><div class="muted">Principal/central BOH stock movement to FOH departmental/other stock.</div></div><div class="card"><form class="filters" method="get"><div><label>From</label><input type="date" name="from" value="<?=e($from)?>"></div><div><label>To</label><input type="date" name="to" value="<?=e($to)?>"></div><button type="submit">Preview</button><a href="export_boh_foh.php?format=xls&from=<?=urlencode($from)?>&to=<?=urlencode($to)?>">Excel</a><a href="export_boh_foh.php?format=csv&from=<?=urlencode($from)?>&to=<?=urlencode($to)?>">CSV</a></form></div><div class="card"><div class="stats"><div class="stat"><b><?=count($rows)?></b><span>Movements</span></div><div class="stat"><b><?=number_format($total)?></b><span>Total quantity moved</span></div><div class="stat"><b>BOH → FOH</b><span>Movement type</span></div></div></div><div class="card"><div class="tablewrap"><table><thead><tr><th>Moved At</th><th>RFID</th><th>Item</th><th>Code</th><th>Qty</th><th>From</th><th>To</th><th>Department</th><th>Moved By</th><th>Device</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e((string)$r['moved_at'])?></td><td><?=e((string)$r['uid'])?></td><td><?=e((string)$r['item_name'])?></td><td><?=e((string)($r['item_code']??''))?></td><td><?=e((string)$r['quantity'])?></td><td><?=e((string)$r['from_zone'])?></td><td><?=e((string)$r['to_zone'])?></td><td><?=e((string)($r['to_department']??''))?></td><td><?=e((string)($r['moved_by']??''))?></td><td><?=e((string)($r['device_uid']??''))?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="10">No movement records found.</td></tr><?php endif; ?></tbody></table></div></div></div></body></html>
