<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
$q=trim($_GET['q']??''); $zone=strtoupper($_GET['zone']??'ALL'); $dept=trim($_GET['department']??'ALL'); $stock=$_GET['stock']??'ALL';
if(!in_array($zone,['ALL','BOH','FOH'],true))$zone='ALL'; if(!in_array($stock,['ALL','LOW','EMPTY'],true))$stock='ALL';
function esc($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$rows=[]; $deps=[]; $r=$conn->query("SELECT DISTINCT branch FROM hod_stock WHERE branch<>'' ORDER BY branch"); while($x=$r->fetch_assoc())$deps[]=$x['branch'];
if($zone!=='FOH'){
 $sql="SELECT p.id,p.product_code,p.barcode,p.serial_number,p.qr_value,p.rfid_uid,ps.name item_name,ps.brand,ps.qty quantity,'BOH' zone,'Principal / BOH' location,ps.branch department FROM inventory_products p JOIN principal_stock ps ON ps.id=p.principal_stock_id WHERE 1=1";
 if($q!=='')$sql.=" AND (p.product_code LIKE ? OR p.barcode LIKE ? OR p.serial_number LIKE ? OR p.qr_value LIKE ? OR p.rfid_uid LIKE ? OR ps.name LIKE ? OR ps.brand LIKE ?)"; if($stock==='LOW')$sql.=' AND ps.qty BETWEEN 1 AND 5'; if($stock==='EMPTY')$sql.=' AND ps.qty<=0';
 $s=$conn->prepare($sql);if($q!==''){ $like="%$q%";$s->bind_param('sssssss',$like,$like,$like,$like,$like,$like,$like);} $s->execute();$rows=array_merge($rows,$s->get_result()->fetch_all(MYSQLI_ASSOC));$s->close();
}
if($zone!=='BOH'){
 $sql="SELECT p.id,p.product_code,p.barcode,p.serial_number,p.qr_value,p.rfid_uid,ps.name item_name,ps.brand,h.qty quantity,'FOH' zone,CONCAT('HOD / FOH - ',h.branch) location,h.branch department FROM inventory_products p JOIN principal_stock ps ON ps.id=p.principal_stock_id JOIN hod_stock h ON h.name=ps.name AND h.brand=ps.brand WHERE 1=1";
 if($q!=='')$sql.=" AND (p.product_code LIKE ? OR p.barcode LIKE ? OR p.serial_number LIKE ? OR p.qr_value LIKE ? OR p.rfid_uid LIKE ? OR ps.name LIKE ? OR ps.brand LIKE ?)"; if($dept!=='ALL')$sql.=' AND h.branch=?'; if($stock==='LOW')$sql.=' AND h.qty BETWEEN 1 AND 5'; if($stock==='EMPTY')$sql.=' AND h.qty<=0';
 $s=$conn->prepare($sql);$types='';$args=[];if($q!==''){ $like="%$q%";$types='sssssss';$args=[$like,$like,$like,$like,$like,$like,$like];}if($dept!=='ALL'){$types.='s';$args[]=$dept;}if($types!=='')$s->bind_param($types,...$args);$s->execute();$rows=array_merge($rows,$s->get_result()->fetch_all(MYSQLI_ASSOC));$s->close();
}
usort($rows,fn($a,$b)=>[$a['item_name'],$a['zone'],$a['department']]<=>[$b['item_name'],$b['zone'],$b['department']]);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Product Finder</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#17202a;font:14px system-ui,Arial}.shell{max-width:1400px;margin:auto;padding:20px}.hero{background:linear-gradient(135deg,#0b1930,#155d78);color:#fff;padding:25px;border-radius:22px}.hero h1{margin:6px 0;font-size:30px}.hero p{opacity:.85}.hero a{color:#fff}.filters,.panel{background:#fff;border:1px solid #e1e7ef;border-radius:18px;padding:18px;margin-top:16px;box-shadow:0 5px 20px #17202a0b}.filters{display:grid;grid-template-columns:2.2fr 1fr 1fr 1fr auto;gap:10px}.field label{display:block;font-size:12px;font-weight:700;color:#687586;margin-bottom:6px}.field input,.field select,button,.btn{width:100%;padding:12px;border:1px solid #ccd5df;border-radius:10px;background:#fff;text-decoration:none;color:#17202a}.primary{background:#1666c5;color:#fff;border-color:#1666c5;font-weight:700}.summary{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.pill{padding:8px 12px;border-radius:999px;background:#eef4fa}.tablewrap{overflow:auto}table{width:100%;min-width:1100px;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid #e7ebf0;text-align:left}th{font-size:11px;color:#687586;background:#fafbfd}.zone{padding:5px 9px;border-radius:999px;background:#eef4fa;font-weight:800}.code{font-family:monospace;font-weight:700}.muted{color:#687586;font-size:12px}.empty{text-align:center;padding:35px;color:#687586}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}.wide{grid-column:1/-1}}@media(max-width:560px){.filters{grid-template-columns:1fr}}
</style></head><body><main class="shell"><section class="hero"><small>COLLEGE INVENTORY • UNIVERSAL SEARCH</small><h1>Product Finder</h1><p>Find the same product across Principal BOH and HOD FOH using Product ID, Product Code, Barcode, QR, Serial Number or RFID UID.</p><a href="index.php">← Inventory Control Center</a></section><form class="filters" method="get"><div class="field wide"><label>Universal Search</label><input name="q" value="<?=esc($q)?>" placeholder="Code / barcode / QR / serial / RFID / product / brand"></div><div class="field"><label>Stock Location</label><select name="zone"><option value="ALL" <?=$zone==='ALL'?'selected':''?>>All BOH + FOH</option><option value="BOH" <?=$zone==='BOH'?'selected':''?>>BOH — Principal</option><option value="FOH" <?=$zone==='FOH'?'selected':''?>>FOH — HOD</option></select></div><div class="field"><label>Department</label><select name="department"><option value="ALL">All Departments</option><?php foreach($deps as $d):?><option value="<?=esc($d)?>" <?=$dept===$d?'selected':''?>><?=esc($d)?></option><?php endforeach;?></select></div><div class="field"><label>Stock Status</label><select name="stock"><option value="ALL">All Stock</option><option value="LOW" <?=$stock==='LOW'?'selected':''?>>Low (1–5)</option><option value="EMPTY" <?=$stock==='EMPTY'?'selected':''?>>Empty (0)</option></select></div><button class="primary">Search</button></form><div class="summary"><span class="pill"><b><?=count($rows)?></b> stock records</span><a class="btn" style="width:auto" href="export.php?<?=http_build_query($_GET)?>">Export Excel</a><a class="btn" style="width:auto" href="export.php?format=csv&amp;<?=http_build_query($_GET)?>">Export CSV</a></div><section class="panel"><div class="tablewrap"><table><thead><tr><th>Product</th><th>Code</th><th>Barcode</th><th>Serial</th><th>QR</th><th>RFID</th><th>Location</th><th>Department</th><th>Qty</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9" class="empty">No matching product found.</td></tr><?php else:foreach($rows as $r):?><tr><td><b><?=esc($r['item_name'])?></b><div class="muted"><?=esc($r['brand'])?></div></td><td class="code"><?=esc($r['product_code'])?></td><td><?=esc($r['barcode']?:'—')?></td><td><?=esc($r['serial_number']?:'—')?></td><td><?=esc($r['qr_value']?:'—')?></td><td><?=esc($r['rfid_uid']?:'—')?></td><td><span class="zone"><?=esc($r['zone'])?></span><div class="muted"><?=esc($r['location'])?></div></td><td><?=esc($r['department']?:'—')?></td><td><b><?=esc($r['quantity'])?></b></td></tr><?php endforeach;endif;?></tbody></table></div></section></main></body></html>
